# Generated by Django 5.2 on 2025-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(default='', max_length=30)),
                ('email_usuario', models.CharField(default='', max_length=30)),
                ('senha_usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
