# Generated by Django 5.2 on 2025-05-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=50)),
                ('sinopse_livro', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_usuarios', to='catalogo.livro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_livros', to='catalogo.usuario')),
            ],
        ),
    ]
